x = int(input("enter x"))
y = int(input("enter y"))
z = int(input("enter z"))

print( x > y )
print( z < y )
print( z == x )
print( z >= y )
print( y == x )
print( x != z )
print( y >= z )
print( x <= z )
print( z == x )
print( y == x )